#\u670D\u52A1\u540D\u79F0
spring:
  application:
    name: micr-dataservice
    #\u6570\u636E\u6E90
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ylb?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 7777777
  redis:
    host: localhost
    port: 6379

#dubbo\u914D\u7F6E
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.bjpowernode.dataservice.service
  protocol:
    name: dubbo
  provider:
    timeout: 5000
    retries: 0
#mybatis\u914D\u7F6E
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.bjpowernode.api.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
