server:
  port: 9000
  servlet:
    context-path: /pay
spring:
  application:
    name: micr-pay
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.bjpowernode
  consumer:
    timeout: 50000
    retries: 0
    check: false
