spring:
  application:
    name: micr-task
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.bjpowernode.task
  consumer:
    check: false
    timeout: 500000
    retries: 0
