server:
  port: 8000
  servlet:
    context-path: /api
spring:
  application:
    name: micr-web
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379

dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.bjpowernode.web
  consumer:
    check: false
    timeout: 5000
    retries: 0


#配置短信服务接口
jdwx:
  sms:
    url: https://way.jd.com/chuangxin/dxjk
    reg-content: 【创信】你的注册验证码是：%s，3分钟内有效！
    login-content: 【创信】你的登录验证码是：%s，10分钟内有效！
    appkey: 953baed688785c86bded933eb3ccd2b6
